name: Generate Featured Discord Threads HTML

on:
  schedule:
    - cron: "*/5 * * * *" # 5 mins
  workflow_dispatch: # manual triger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jinja2  # Add jinja2 if not in requirements.txt

      - name: Run Discord bot to fetch featured threads
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          DISCORD_FORUM_CHANNEL_IDS: ${{ secrets.DISCORD_FORUM_CHANNEL_IDS }}
          DISCORD_FEATURED_TAG_NAME: ${{ secrets.DISCORD_FEATURED_TAG_NAME }}
        run: python bot.py

      - name: Commit dist folder
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          git commit -m "Update featured threads [skip ci]" || echo "No changes to commit"
          git push
